### ISSUE TITLE
After upgrade to 1.1.0, mix test no longer runs

### ISSUE THREAD

**Issue by nocivus** [elixir-plug/plug_crypto#10]
`mix test`
```
12:33:08.706 [info]  Application plug exited: exited in: Plug.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Plug.start/2 is undefined (module Plug is not available)
            Plug.start(:normal, [])
            (kernel 6.5.1) application_master.erl:277: :application_master.start_it_old/4

12:33:08.708 [info]  Application plug_crypto exited: :stopped

12:33:08.709 [info]  Application mime exited: :stopped

12:33:08.710 [info]  Application phoenix_pubsub exited: :stopped

12:33:08.710 [info]  Application telemetry exited: :stopped

12:33:08.711 [info]  Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:plug, {:bad_return, {{Plug, :start, [:normal, []]}, {:EXIT, {:undef, [{Plug, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    (phoenix 1.4.12) lib/mix/tasks/compile.phoenix.ex:11: Mix.Tasks.Compile.Phoenix.run/1
    (mix 1.10.0) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.0) lib/mix/tasks/compile.all.ex:76: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.10.0) lib/mix/tasks/compile.all.ex:56: Mix.Tasks.Compile.All.do_compile/4
    (mix 1.10.0) lib/mix/tasks/compile.all.ex:27: anonymous fn/2 in Mix.Tasks.Compile.All.run/1
    (mix 1.10.0) lib/mix/tasks/compile.all.ex:43: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.10.0) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.0) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1
```

Using elixir 1.10.0

**Comment by josevalim** [comment]
What is the output of your `mix deps`? I have a Phoenix app running on `plug_crypto 1.1.0`  with no problems. Have you tried running `rm -rf _build` and then `mix test`?

**Comment by nocivus** [comment]
Seems to work after removing `_build` and recompiling. Thanks José!
